Igalia/wolvic

.github/workflows/ci.yml
app/build.gradle

This is a temptative implementation of CI for push and PRs using gradle and github actions

CI for push & PR using gradle and Github actions

---

app/build.gradle
app/src/hvr3dof/AndroidManifest.xml

Note: I used com.igalia.wolvic.tdof instead of 3dof because Android complains about using numbers or other symbols in the package name

Create a different flavor for HVR 3DOF builds

---

app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/search/SearchEngineWrapper.java
app/src/common/shared/com/igalia/wolvic/telemetry/TelemetryService.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/SelectionActionWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/PrivacyOptionsView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/SearchEngineView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/SettingsView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/SettingsWidget.java
app/src/main/res/layout/options_privacy.xml
app/src/main/res/layout/options_search_engine.xml
app/src/main/res/values/non_L10n.xml
app/src/main/res/values/strings.xml

This PR adds a new settings view to pick the preferred search engine from those suggested by the current language and location.

Support for user configurable search engine

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/ui/viewmodel/SettingsViewModel.java
app/src/common/shared/com/igalia/wolvic/ui/views/TabView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/HamburgerMenuWidget.java
app/src/main/res/layout/settings.xml

Enable Firefox Accounts

---

app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-es-rES/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-nb-rNO/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-nn-rNO/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sv-rSE/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Update storage permission setting from "Read External Storage" to "Storage" in all supported languages.
This supersedes [PR#103](https://github.com/Igalia/wolvic/pull/103).

Storage permission string

---

app/src/common/shared/com/igalia/wolvic/browser/engine/SessionStore.java

This Debug observer is ran in a non UI thread, and it causes problem calling WebLayer APIs in a different thread.

Run storeSubscription observer on the main thread

---

app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java

By default, order downloads by most recent.

Sort Downloads by most recent first

---

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp

For the Quest2 devices, controllers used to show some abnormal rotation
to the top inside WebXR sessions. The problem was that we were applying
a 45º rotation to the controller transform instead of to the immersive
beam transform.

Fix 6DoF controllers rotation in WebXR

---

app/src/main/res/values-da/strings.xml

This PR is an end-to-end test of the new translation process we are setting up for Wolvic using [Weblate](https://weblate.org/).
The strings should have been reviewed already by approved reviewers on Weblate. But as a side note, it is still not completely clear to me whether we should defer the review to the PR, which we have to open anyway to merge into `main` branch; and remove the requirement of review on Weblate side. Reviewing twice seems like unnecessary overhead.

Add translations from Weblate (Danish)

---

app/src/main/res/values-fr/strings.xml

French translations coming from Weblate, courtesy of @fred-wang and an external contributor.
Thank you!

[i10n] Update translations to French 

---

app/src/main/res/values-zh-rCN/strings.xml

Via Weblate, courtesy of Ziran Sun. Thanks!

[i10n] Update translations to Chinese (Simplified)

---

app/src/main/res/values-fr/strings.xml

Currently translated at 100.0% (594 of 594 strings) \o/
Thanks, @fred-wang!

[i10n] Update translations to French

---

app/src/main/res/values-ja/strings.xml

Via Weblate, currently translated at 96.2% (572 of 594 strings)
Thanks, @takikawa!

[i10n] Update translations to Japanese

---

app/src/main/res/values-gl/strings.xml

Courtesy of Mar Castro and @jaragunde.
I think @juanjosanchez has many more translations to Galizian, probably in a local copy. It would be nice to sync with Mar and Jacobo to get all those submitted to Weblate.
Thanks!

[i10n] Add translations to Galician

---

app/src/main/res/values-es-rES/strings.xml

Currently translated at 100.0% (594 of 594 strings) \o/. 
Thanks, @jaragunde.

[i10n] Update translations to Spanish

---

app/src/main/res/values-ko/strings.xml

Via Weblate, currently translated at 99.4% (591 of 594 strings)
Thank you, Yeunjoo Choi!

[i10n] Update translations to Korean

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/VoiceSearchWidget.java

When the speech recognition service changes, our `VRBrowserApplication` updates its recognizer instance to one that uses the selected service.
The `VoiceSearchWidget` gets this recognizer instance and uses it to carry out the actual process of voice recognition.
The problem is that when the service changes, `VoiceSearchWidget` does not update its recognizer instance to be the same as the new one in `VRBrowserApplication`. This meant that voice recognition kept using the old service and not the new one.
This change updates the speech recognizer whenever `VoiceSearchWidget` starts listening for a new input.

Update the speech recognizer

---

app/src/main/res/values-pt-rBR/strings.xml

Via Weblate. Thanks Tiago Vignatti!

[i10n] Added translations to Portuguese (Brazil)

---

app/src/main/res/values-ko/strings.xml

More Korean goodies via Weblate, currently translated at 99.5% (597 of 600 strings)
Thanks, Yeunjoo Choi!

[l10n] Update translations to Korean

---

app/src/main/res/values-fr/strings.xml

Via Weblate, currently translated at 100.0% (600 of 600 strings)
Thanks, @fred-wang!

[l10n] Update translations to French

---

app/src/main/res/values-es-rES/strings.xml

Via Weblate, currently translated at 100.0% (600 of 600 strings)
Courtesy of @jaragunde, thanks!

[l10n] Update translations to Spanish

---

app/src/main/res/values-zh-rCN/strings.xml

Via Weblate, currently translated at 100.0% (600 of 600 strings)
Thanks, @ziransun!

[l10n] Update translations to Chinese (Simplified)

---

app/src/main/res/values-gl/strings.xml

Via Weblate, now at 100%!
Courtesy of @juanjosanchez, thanks!

[l10n] Update translations to Galician

---

app/src/main/res/values-ru/strings.xml

Via Weblate, currently translated at 96.1% (577 of 600 strings).
Thanks `fmwolfiechad`!

[l10n] Update translations to Russian

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/BrowserDisplay.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/DisplayImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/FullScreenCallbackImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/NavigationCallbackImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/NewTabCallbackImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/PanZoomCrontrollerImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/ResultImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/RuntimeImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionStateImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SettingsImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabCallbackImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TextInputImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/WebExtensionControllerImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/WebExtensionImpl.java

Depends on #75, #76, #77, #78 and #79

Initial WebLayer backend implementation

---

app/src/main/res/values-sv-rSE/strings.xml

Via Weblate, currently translated at 99.0% (594 of 600 strings)
Thanks, Luna Jernberg!

[l10n] Update translations to Swedish

---

app/src/main/res/values-es-rES/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-zh-rCN/strings.xml

Translated via Weblate, this series makes Galician, Spanish, French and Chinese (simplified) again translated at 100% (602 of 602 strings).
Chinese courtesy of @ziransun and French by @fred-wang, thanks!

[l10n] Update translations to various languages

---

app/src/main/res/values-es-rES/strings.xml

Currently translated at 100.0% (603 of 603 strings)

[l10n] Update translations to Spanish (Spain)

---

app/build.gradle
app/src/hvr/java/com/igalia/wolvic/PlatformActivity.java

Enable `HiAnalytics` in `PlatformActivity`.
Rename `HVR_ML_API_KEY` to `HVR_API_KEY`.

Enable analytics for Huawei devices

---

app/src/common/shared/com/igalia/wolvic/browser/WebAppsStore.java
app/src/common/shared/com/igalia/wolvic/browser/components/BrowserIconsHelper.kt
app/src/common/shared/com/igalia/wolvic/browser/engine/Session.java
app/src/common/shared/com/igalia/wolvic/ui/adapters/WebApp.java
app/src/common/shared/com/igalia/wolvic/ui/adapters/WebAppsAdapter.java
app/src/common/shared/com/igalia/wolvic/ui/callbacks/WebAppItemCallback.java
app/src/common/shared/com/igalia/wolvic/ui/viewmodel/WebAppsViewModel.java
app/src/common/shared/com/igalia/wolvic/ui/viewmodel/WindowViewModel.java
app/src/common/shared/com/igalia/wolvic/ui/views/NavigationURLBar.java
app/src/common/shared/com/igalia/wolvic/ui/views/library/LibraryPanel.java
app/src/common/shared/com/igalia/wolvic/ui/views/library/WebAppsView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/TrayWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/Windows.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/InstallWebAppDialogWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/PromptDialogWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/HamburgerMenuWidget.java
app/src/main/res/drawable/ic_icon_save.xml
app/src/main/res/drawable/ic_icon_webapps.xml
app/src/main/res/drawable/ic_web_app_registration.xml
app/src/main/res/layout/library.xml
app/src/main/res/layout/navigation_url.xml
app/src/main/res/layout/prompt_dialog.xml
app/src/main/res/layout/web_app_item.xml
app/src/main/res/layout/webapps.xml
app/src/main/res/values/strings.xml

This PR is the initial implementation of an UI for Web apps.
The user can add a new Web app by clicking on the `"Save Web app…"` button on the top bottom menu on the browser. This opens a dialog with the Web app's details. There is also a button in the URL bar with the same functionality.
Saved Web apps are displayed in a new tab in the Library.

Initial UI for Web apps

---

app/src/common/shared/com/igalia/wolvic/ui/views/TabView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/SuggestionsWidget.java
app/src/main/res/layout/list_popup_window_item.xml
app/src/main/res/layout/tab_view.xml
app/src/main/res/values/dimen.xml

This small PR adds favicons to the autocomplete suggestions and the tab switcher.

Display favicons in suggestions and tabs

---

app/src/common/shared/com/igalia/wolvic/browser/engine/Session.java

To give Wolvic more visibility we are replacing our default user agent string, coming from gecko-dev, by a hard-coded version on Wolvic side that replaces the string `Firefox/<version>` by `Wolvic/<version>`.
The exising UA overrides continue to work as usual, but all other requests will have the new default UA, which currently is:
`Mozilla/5.0 (Android 10; Mobile VR; rv:105.0) Gecko/105.0 Wolvic/1.2`
Note that the Youtube extension has its own UA override, and it is needed for 2D fullscreen videos to work properly.

Sets a default user agent and adds `Wolvic/<version>` to it

---

app/build.gradle

Addresses #283 
The plugin should get added only for HVR builds now, non-HVR builds will ignore it

[Build] #283 Move com.huawei.agconnect plugin into condition

---

app/src/main/cpp/BrowserWorld.cpp
app/src/main/cpp/BrowserWorld.h

Remove BrowserWorld::CreateEnvironment as it isn't used anywhere.

Remove dead code

---

app/src/main/cpp/ControllerContainer.cpp
app/src/main/cpp/ExternalVR.cpp

Fix a small issue that I found when compiling on Mac.

Include assert.h

---

app/src/openxr/cpp/DeviceDelegateOpenXR.cpp

Platforms like Meta or Pico allow a maximum of 16 layers to be submitted for a given frame to the compositor.
It's unlikely that we'll reach that limit with our current setup but it does not hurt to prevent us from doing so. 
Note that if a layer is skipped for a given frame it'll be very likely sent in any of the followup frames.
We do the same for the OculusVR backend so it makes sense to do it also for OpenXR.

[OpenXR][XRlayers] Limit the amount of layers sent to the compositor

---

app/src/main/res/layout/web_app_item.xml

Remove the background color for icons, since it does not make them look good in most cases. Correct the position of the Trash button.

Visual issues in Web apps list

---

app/src/main/res/values-pt-rBR/strings.xml

Via Weblate, currently translated at 100.0% (632 of 632 strings).
Thank you @nasseralm and @nickdiego!

[l10n] Update translations to Portuguese (Brazil)

---

app/src/main/res/values-ja/strings.xml

Via Weblate, currently translated at 98.1% (620 of 632 strings)
Thank you, @takikawa!

[l10n] Update translations to Japanese

---

app/src/openxr/cpp/DeviceDelegateOpenXR.cpp

We recently added support to reorientation changes in the OpenXR backend. It was
working perfectly for 6DoF devices however in the case of 3DoF devices the widget
position was locked to head's. That's because we were re-using the firstPose field to
check whether a recentering happened (as we knew it's set to null on those events).
However it's also set to null in other cases (EnterVR for example), and also not 
properly updated in 3DoF devices. So we better use a different field to store that
information.

[OpenXR] Fix reorientation for 3DoF devices

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java

This CL changes to access InputConnection API through its handler to solve a crash caused by a strict thread check in Chromium. Also, this CL adds a flag to prevent an issue of the other two selection positions being updated repeatedly. Chromium processes asynchronously each InputConnection API below, causing this issue of changing the cursor position back and forth, so this flag will ignore the first notification of updateSelection.

Access InputConnection API through its handler

---

app/src/common/shared/com/igalia/wolvic/ui/keyboards/KoreanKeyboard.java

This CL fixes the next composition issue of combined consonant when vowel is added in Korean.
Example : `않` + `ㅏ` should be `안하` instead of `않ㅏ`.

Fix the next composition of combined consonant in Korean

---

app/src/main/res/values-pt/strings.xml

Vía Weblate, currently translated at 100.0% (632 of 632 strings).
Courtesy of @SantosSi, thanks!

[l10n] Update translations to Portuguese

---

app/src/main/res/drawable/fullscreen_button.xml
app/src/main/res/drawable/fullscreen_button_first.xml
app/src/main/res/drawable/fullscreen_button_last.xml
app/src/main/res/layout/top_bar.xml

Partially fixes https://github.com/Igalia/wolvic/issues/582

Top bar layout uses privateModeBackground attribute

---

app/src/openxr/cpp/DeviceDelegateOpenXR.cpp
app/src/openxr/cpp/OpenXRLayers.h

Reverts Igalia/wolvic#554
It caused a regression in OpenXR layers

Revert "Properly destroy all OpenXRSwapChain instances before destroying the XRInstance"

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/DeprecatedVersionDialogWidget.java
app/src/common/shared/com/igalia/wolvic/utils/DeviceType.java
app/src/hvr/java/com/igalia/wolvic/PlatformActivity.java
app/src/lynx/java/com/igalia/wolvic/PlatformActivity.java
app/src/main/res/layout/deprecated_version_dialog.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values/strings.xml
app/src/noapi/java/com/igalia/wolvic/PlatformActivity.java
app/src/oculusvr/java/com/igalia/wolvic/PlatformActivity.java
app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
app/src/picoxr/java/com/igalia/wolvic/PlatformActivity.java
app/src/wavevr/java/org/mozilla/vrbrowser/PlatformActivity.java

Implement a startup dialog for App Lab users, informing them that they should install Wolvic from the Oculus Store.

Dialog for App Lab users

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java

Implement basic navigation methods using WebContents' navigation controller. This allows the browser's URL bar (including back, forward and reload buttons) to work with the Chromium backend. Method getUriFromString() is reused from the weblayer based implementation.

Chromium: Implement basic navigation using URL bar

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabMediaSessionObserver.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabWebContentsDelegate.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabWebContentsObserver.java

- Add TabMediaSessionObserver for the media control
- Add TabWebContentsDelegate for fullscreen
Precursor CL is Igalia/wolvic-chromium#7

Support FullScreen & Media

---

app/CMakeLists.txt
app/build.gradle
app/src/main/cpp/BrowserWorld.cpp
app/src/main/cpp/EngineSurfaceTexture.cpp
app/src/main/cpp/EngineSurfaceTexture.h
app/src/main/cpp/ExternalBlitter.cpp

So that we could use it in the multibackend architecture

Refactor surface texture

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java

This PR fixes an issue where the tray will sometimes become visible in fullscreen mode.

Hide the tray when in fullscreen or kiosk mode

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java

For testing purposes, this PR introduces a way to exit kiosk mode by clicking seven times in a row on the window menu button.

Kiosk mode flipper for testing

---

app/src/picoxr/AndroidManifest.xml

Reverts Igalia/wolvic#661
Looks like permission is not properly added

Revert "[PicoXR] Enable WAKE_LOCK permission to allow app resuming"

---

app/src/openxr/cpp/OpenXRInputSource.cpp

Reverts Igalia/wolvic#689
Looks like it degrades the pinching experience more than fixing accidental clicks

Revert "Smoothing filter for hand clicks"

---

app/src/main/res/values-es-rES/strings.xml

Via Weblate. Currently translated at 100.0% (641 of 641 strings).
Thanks, @gallegonovato and @jaragunde!

[l10n] Update translations to Spanish 

---

app/src/main/res/values-ko/strings.xml

Via Weblate. Currently translated at 100.0% (641 of 641 strings)
Thanks, Hyowon!

[l10n] Update translations to Korean.

---

app/src/main/res/values-fr/strings.xml

Via Weblate. Currently 100% translated.
Thanks J. Lavoie and @fred-wang!

[l10n] Update translations to French 

---

README.md

Add `third_party/ovr_openxr_mobile_sdk/` to `README.md`

---

app/src/main/res/values-zh-rCN/strings.xml

- Service Terms 服务条款 -> User Agreement “用户协议”
- Privacy Policy WOLVIC基本隐私政策 -> “隐私政策”

Update a few Chinese translations 

---

app/build.gradle
app/src/hvr/java/com/igalia/wolvic/ContentHolderFragment.java
app/src/hvr/java/com/igalia/wolvic/FirstRunFragment.java
app/src/hvr/java/com/igalia/wolvic/LandingPageFragment.java
app/src/hvr/res/layout/fragment_first_run.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

This PR implements the initial flow for the phone UI in mainland China, which is slightly different from the general one.
The build variable CN_FIRST_RUN_IN_PHONE_UI can be used to select which implementation is used.

Initial flow for mainland China

---

.github/workflows/ci.yml
app/build.gradle

This PR defines the "mainlandChina" store flavour, which includes a specific phone UI.

Define the "mainlandChina" store flavour

---

app/src/common/shared/com/igalia/wolvic/browser/PromptDelegate.java
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-es-rES/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-nb-rNO/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-nn-rNO/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sv-rSE/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Confirmation title, text and button messages as well as their translations are copied from chromium. https://github.com/chromium/chromium/blob/main/components/strings/components_strings_en-GB.xtb
translation id:
- 6451458296329894277
- 8241707690549784388
- 2359808026110333948

Implement POST resubmission confirmation

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SettingsImpl.java

Use Chromium backend's SessionSettings class to support settings user agent mode and user agent override.
depends on https://github.com/Igalia/wolvic-chromium/pull/19

Chromium: Implement User Agent support

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/PromptDialogWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/prompts/PromptData.java

Also, make Confirm Prompt able to configure title gravity.
Resolves issue #778

Use left alignment for the download Confirmation Dialog

---

app/src/common/shared/com/igalia/wolvic/ui/OffscreenDisplay.java
app/src/noapi/java/com/igalia/wolvic/PlatformActivity.java
app/src/oculusvr/java/com/igalia/wolvic/PlatformActivity.java

Resolves #800
https://stackoverflow.com/a/65128718

Modernize deprecated setSystemUiVisibility(int) and related flags

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/prompts/ChoicePromptWidget.java

Fix to keep the selected options for <select>

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java
app/src/common/shared/com/igalia/wolvic/utils/UrlUtils.java

Resolves #390 
Now we can put the developing HTML files into `file:///storage/emulated/0/Android/data/com.igalia.wolvic/files` to get them tested.

File:// uri navigation support

---

app/src/common/shared/com/igalia/wolvic/browser/PromptDelegate.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/prompts/DateTimePromptWidget.java
app/src/main/res/layout/prompt_datetime.xml

Implement DateTime picker Dialog
All five types of date/time related inputs are now supported.
Resolves #423
Supersede #640 as rewriting using a more elegant approach and didn't have a base on that.

Implement DateTime picker Dialog

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/TrayWidget.java

Further address #908
Now we will have a crash if we start Wolvic with WIFI disabled, this PR fixes this

Add a null check to getSignalStrength()

---

app/src/common/shared/com/igalia/wolvic/utils/ConnectivityReceiver.java

The CONNECTIVITY_ACTION constant was deprecated in API level 28. apps should use the more versatile requestNetwork(NetworkRequest, PendingIntent), registerNetworkCallback(NetworkRequest, PendingIntent) or registerDefaultNetworkCallback(NetworkCallback) functions instead for faster and more detailed updates about the network changes they care about.
Resolves #803

Modernize deprecated CONNECTIVITY_ACTION in ConnectivityManager

---

.github/FUNDING.yml

Address #912 
Looks like we only need the handler here

Fix opencollective funding link

---

app/src/common/shared/com/igalia/wolvic/utils/ConnectivityReceiver.java

Reverts Igalia/wolvic#906
It's causing issues as it incorrectly reports connectivity status on program startup in many occasions. The no connection dialog is shown and also the wifi icon is showing no signal.

Revert "Modernize deprecated CONNECTIVITY_ACTION in ConnectivityManager"

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java

Implement DownloadManager.Delegate to use Wolvic's downloads implementation instead of Chromium one.

[Chromium] Implement DownloadManager.Delegate

---

app/src/common/shared/com/igalia/wolvic/ui/views/NavigationURLBar.java

Fix disabling address bar auto-complete feature in settings

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/WidgetManagerDelegate.java

Exit curved mode when playing video in full screen
Resolve #545

Fix 3D Side-By-Side video playing in curved mode

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/HamburgerMenuWidget.java
app/src/main/res/layout/navigation_bar_navigation.xml

Now we show/hide the bar just for find in page
Continue address #974

Add back Find In Page when in kiosk mode

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/browser/engine/SessionStore.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/Windows.java

We will select the tab instead of opening a new tab when the URL has already been opened
Resolves #981

Select tab when opening URL foreground by intent

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SettingsImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabImpl.java

This PR does two things:
* first it enables incognito mode in the UI
* second it uses the new Tab API added https://github.com/Igalia/wolvic-chromium/pull/40 that allows Wolvic to specify whether a new tab should be created in incognito mode

[Chromium] Implement private (incognito) mode

---

app/src/common/gecko/com/igalia/wolvic/browser/api/impl/RuntimeImpl.java
app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/browser/engine/EngineProvider.kt
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/PrivacyOptionsView.java
app/src/main/res/layout/options_privacy.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/non_L10n.xml
app/src/main/res/values/strings.xml

Resolve #489
Tested using no API on my Android phone by [Fiddler Android Traffic Capture](https://docs.telerik.com/fiddler-everywhere/capture-traffic/capture-from-android).

Enable to use system trusted root certificates

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/VoiceSearchWidget.java
app/src/main/res/layout/voice_search_dialog.xml

Make voice input content scrollable and stick to the latest

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/VideoProjectionMenuWidget.java
app/src/main/assets/extensions/fxr_youtube/main.js
app/src/main/cpp/BrowserWorld.cpp
app/src/main/cpp/VRVideo.cpp
app/src/main/cpp/VRVideo.h
app/src/main/res/drawable/ic_icon_videoplayback_3dtopbottom.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Resolve #171
Test video: https://www.youtube.com/watch?v=9ScZRkRUYLM
Test video for YouTube auto format recognition: https://www.youtube.com/watch?v=CvxFiQYeHo0

Add 3D top bottom format support to VR video playing

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/DisplayOptionsView.java
app/src/main/cpp/BrowserWorld.cpp
app/src/main/cpp/VRBrowser.cpp
app/src/main/cpp/VRBrowser.h
app/src/main/res/layout/options_display.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/non_L10n.xml
app/src/main/res/values/strings.xml

That setting is located in display options. The default value varies according to device type.
Resolves #666

Enable starting with passthrough mode

---

app/src/common/shared/com/igalia/wolvic/ui/views/NavigationURLBar.java

This can be a good user experience improvement

Allow exit find in page mode when we press the back button

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/ClearUserDataDialogWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/PrivacyOptionsView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/SettingsView.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/SettingsWidget.java
app/src/main/res/layout/options_privacy.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

This is available in settings, under Privacy & Security section.
When user choose the option, we will prompt user with detailed explanation of what's going to happen
resolve #345

Add option to clear all user data

---

app/src/main/res/layout/deprecated_version_dialog.xml
app/src/main/res/values-es-rES/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-gl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values/strings.xml

Update the launch message of the App Lab version to inform the user that this version will be discontinued soon.
EN, ES, FR, PT and GL translations are included.

Update App Lab message

---

app/src/spaces/AndroidManifest.xml

Changes in the AndroidManifest.xml file requires to run on the latest version of the Spaces platform.

Manifest changes for Spaces

---

app/src/main/assets/extensions/fxr_youtube/main.js

Since YouTube plugin infers video projection types according to words in video title and description, and if `mozVideoProjection` is already there in the url, the plugin will respect the value and won't infer any more.
This works perfectly fine for playing a single video, but if we try to continue playing other projection types of video without leaving the Youtube, the inferred `mozVideoProjection` will get preserved in the url, which makes all the videos continue using the same projection type.
As a result, we should reset the page projection after navigating to a new page that is different from initial page.
Also we should wait for yt-update-title event to happen so that we can get the updated title and description for projection inferring: …

Allow YouTube playing different projection types of VR videos continuously

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabWebContentsObserver.java

GeckoSession uses a HistoryDelegate object (provided by Wolvic) to keep track of history changes. In the case of Chromium the concept is different. We can listen to the events dispatched by the WebContents object and manyally call the HistoryDelegate to record changes in the history. That way we don't need to change anything in the Gecko port and we get history support in Chromium.

[Chromium] Record history

---

app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/browser/engine/EngineProvider.kt
app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java

Reverts Igalia/wolvic#1105
It broke the Settings/library UI. It is no longer possible to properly hover widgets

Revert "Increase logical size and resolution of Web pages"

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/ChromiumPermissionDelegate.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java

This change depends on https://github.com/Igalia/wolvic-chromium/pull/51
Implement ChromiumPermissionDelegate which forwards permission requests sent by Chromium to the Wolvic permission request dialog.

[Chromium] Add permission dialog support

---

props.json

Add the following environments to Wolvic:
- Autumn Forest by Paul (CC BY)
- Basic Sky by Paul (CC BY)
- Barcelona Rooftops by MozillaHubs (CC BY-NC-SA)
- Night Forest With Aurora Sky by Architecture_Interior (CC BY)

Add four new environments

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/WidgetPlacement.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java

Related to our recent changes in #1107
After fix:

Fix selection menu location for web pages

---

app/src/common/shared/com/igalia/wolvic/ui/keyboards/BaseLatinKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/DanishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/DutchKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/EnglishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/FinnishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/FrenchKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/GermanKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/ItalianKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/NorwegianKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/PolishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/RussianKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/SpanishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/SwedishKeyboard.java

Inspiration from Chinese/Japanese candidates input.
Wordlist databases taken from
https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/main/dictionaries/
Script for converting from text format wordlist into sqlite3 databases:
https://gist.github.com/HollowMan6/e4bb09cd9cf6d6cc895c24659c015d06
https://github.com/Igalia/wolvic/assets/43995067/27d45cc6-6045-4d4b-9009-5a3236853321
Resolve https://github.com/Igalia/wolvic/issues/737

Enable word auto complete for Latin keyboards

---

app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/ui/viewmodel/SettingsViewModel.java
app/src/common/shared/com/igalia/wolvic/ui/viewmodel/WindowViewModel.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/WidgetManagerDelegate.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/Windows.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/DisplayOptionsView.java
app/src/main/cpp/BrowserWorld.cpp
app/src/main/cpp/BrowserWorld.h
app/src/main/cpp/WidgetMover.cpp
app/src/main/cpp/WidgetMover.h
app/src/main/res/layout/navigation_bar_fullscreen.xml
app/src/main/res/layout/navigation_bar_navigation.xml
app/src/main/res/layout/options_display.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/non_L10n.xml
app/src/main/res/values/strings.xml

I also tried to enable the drag and move at Z direction but it seems like we still have some issue with that, and it maybe okay to not enable Z direction move as long as we have something like #734 landed.
Now we hardcode the max/min X/Y, later if we can change into spherical move, we may then be able to remove that limit.
Partially resolve #927 and #99
https://github.com/Igalia/wolvic/assets/43995067/631b6f15-096e-4004-9666-b3ff25792e78
https://github.com/Igalia/wolvic/assets/43995067/58d35451-66a0-495f-82c1-d068dc1e91cc

Enable drag and move windows at X & Y direction

---

app/src/main/res/drawable/settings_group_borders.xml
app/src/main/res/layout/options_display.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

So that users can recognize them and use with caution

Add group for experimental features in display settings

---

props.json

Add the following environments for Wolvic 1.5.2:
- Pretville Cinema  (CC0)
- Winter Night by Paul (CC-BY)

Add two new environments for 1.5.2

---

props.json

Rename the environment to "Winter Night", which is the correct name.
See:
https://sketchfab.com/3d-models/free-skybox-winter-night-9cf1663e9a8647b987ce4f439c22ff50

Rename environment to "Winter Night"

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/PromptDelegateImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabWebContentsDelegate.java

Show form repost warning dialog by using the corresponding Chromium method in TabWebContentsDelegate.java.

[Chromium] Implement form repost warning dialog

---

app/build.gradle
app/src/debug/res/values/non_L10n.xml
app/src/main/res/values/non_L10n.xml

This PR is about adding support to specify the app_name per flavour giving us great flexibility and also allowing multiple simultaneos installations of Wolvic in the same device

Better app name

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java

Extract the parameter names used in the Intents and custom URIs to launch Wolvic into public constant String values.

Extract launch parameter names to constants

---

app/src/common/shared/com/igalia/wolvic/utils/EnvironmentsManager.java

Apply the same review feedback related to code logic in #1131 to the environments manager as well.
- Add null check before getEnvironmentPayload is called
I prefer not to apply the code styling things to keep the commit history clean. Feel free to ask me to apply those code styles to the Environments as well if you prefer.

Environments manager code logic cleanup

---

app/build.gradle
app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/VRBrowserApplication.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/BaseLatinKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/ChinesePinyinKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/ChineseZhuyinKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/DanishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/DutchKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/EnglishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/FinnishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/FrenchKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/GermanKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/ItalianKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/KeyboardInterface.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/NorwegianKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/PolishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/RussianKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/SpanishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/SwedishKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/AppServicesProvider.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/WidgetManagerDelegate.java
app/src/common/shared/com/igalia/wolvic/utils/DictionariesManager.java
app/src/common/shared/com/igalia/wolvic/utils/DictionaryUtils.java
app/src/common/shared/com/igalia/wolvic/utils/RemoteProperties.kt
versions.gradle

Resolve #1128
We remove the SQLiteAssetHelper dependency, store the database into the dedicated database path. Now the auto-complete will be on after the dictionaries are downloaded successfully.
We continue to store Chinese databases locally as those should be available immediately to type in Chinese.

Download Keyboard dictionaries on demand

---

app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/ui/keyboards/BaseLatinKeyboard.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/DisplayOptionsView.java
app/src/common/shared/com/igalia/wolvic/utils/DictionariesManager.java
app/src/main/res/layout/options_display.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/non_L10n.xml
app/src/main/res/values/strings.xml

As suggested in https://github.com/Igalia/wolvic/pull/1131#issuecomment-1895690337

Allow disabling Latin Keyboard input auto complete

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/VRBrowserApplication.java
app/src/main/res/drawable/headlock_toggle_button_states.xml
app/src/main/res/layout/visionglass_layout.xml
app/src/visionglass/cpp/DeviceDelegateVisionGlass.cpp
app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java

This PR involves the following changes in the VisionGlass UI:
1. Added a Home button that loads the home page
2. Improved Phone UI design. Added layout containers, better handling of empty space, colors...
3. Add headlock support

[VisionGlass] Phone UI improvements and additions

---

app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java

Structure the code so it responds to changes in connected devices, USB permissions, etc.
Implement OnConnectionListener to get notified when the device is connected and disconnected.
Receive notifications when the USB permission has been granted.
Try to ensure that the state of the app remains consistent.
Add debug logs.

Clean up launch of Vision Glass

---

app/src/common/shared/com/igalia/wolvic/ui/OffscreenDisplay.java
versions.gradle

Modernize deprecated getMetrics(DisplayMetrics) in Display

---

app/src/main/res/values-pt-rBR/strings.xml

Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/pt_BR/

Translated using Weblate (Portuguese (Brazil)) 

---

app/src/main/res/values-sv-rSE/strings.xml

Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/sv/

Translated using Weblate (Swedish) 

---

app/src/main/res/values-ru/strings.xml

Currently translated at 97.3% (655 of 673 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/ru/

Translated using Weblate (Russian)

---

app/src/main/res/values-es-rES/strings.xml

Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/es/

Translated using Weblate (Spanish)

---

app/src/main/res/values-de/strings.xml

Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/de/

Translated using Weblate (German)

---

app/src/main/res/values-zh-rCN/strings.xml

Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/zh_Hans/

Translated using Weblate (Chinese (Simplified))

---

app/src/main/res/values-zh-rTW/strings.xml

Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/zh_Hant/

Translated using Weblate (Chinese (Traditional))

---

app/src/main/res/values-fi/strings.xml

Currently translated at 60.4% (407 of 673 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/fi/

Translated using Weblate (Finnish)

---

props.json

Release blog post: https://wolvic.com/blog/release_1.6
New environments: meadow, abovetheclouds, milkyway2020.

Update props.json for 1.6.0

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java

So far Wolvic has been refreshing the battery level of headset and controllers with a 1s frequency. That's definitely way too much because the change rate does not require that level of granularity.
What's more, the docs[1] mention "the impact of constantly monitoring the battery level has a greater impact on the battery than your app's normal behavior".
[1] https://developer.android.com/training/monitoring-device-state/battery-monitoring#MonitorLevel

Refresh battery levels less frequently

---

props.json

Amend props.json to include the environments and dictionaries that were available for earlier versions, so they are also available in the new 1.6.0 version.

Include environments and dictionaries from previous versions

---

app/src/main/res/drawable/settings_group_borders.xml
app/src/main/res/layout/options_display.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

This reverts commit 77c36d5117193774b397de48b4efac7b273005b4.

Remove label for experimental features in display settings

---

app/build.gradle

Huawei VR: https://wolvic.com/zh/start/index.html
Huawei Vision Glass: https://wolvic.com/zh/start/hvg.html
PICO: https://wolvic.com/zh/start/pico.html

Default homepages for China releases

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/PromptDelegateImpl.java

This patch implements the file selection's prompt that uses `<input type=file>` in the web page.

[Chromium] Implement File Selection prompt

---

app/src/openxr/cpp/OpenXRInputSource.cpp

This reverts commit 54c9c44e82801072fd6a113a33796e6b0c755f2f.

Revert "Disable 1€ filtering for Magic Leap 2"

---

app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java

This PR addresses the issue of the browser window not being rendered in front of the user when the application starts.
Fixes #1280

[VisionGlass] Initial orientation

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/SignOutDialogWidget.java

The FxA signing out process offers the user the possibility of clearing out the bookmarks, history and logins store. This logic is implemented by deleting directly the sqlite files that contain the databse for such user data. This file is created during the app startup process and there is no way to do it without a restart. 
The main goal of this PR is to ensure the signout procedure doesn't clear the storage without proceeding with the restart, so that we avoid the inconsistent state described on the issue #1307. Hence, we are going to launch a confirmation dialog to ensure the user is willing to proceed with the restart, going back to the sign-out dialog otherwise so that the user uncheck the option to clearing up the storage or even cancel the signout process altogether.
Fixes #1307

Restart Wolvic after clearing the Library store

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/ChromiumPermissionDelegate.java

depends on https://github.com/Igalia/wolvic-chromium/pull/84
Implements requesting android permissions if required whenever a corresponding content permission is requested. This logic is based on a new parameter "androidPermissionTypes" added in wolvic-chromium.

[Chromium] Implement Android permissions

---

app/src/main/res/values-da/strings.xml

Currently translated at 99.7% (671 of 673 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/da/

Translated using Weblate (Danish)

---

app/src/main/res/values-uk/strings.xml

Currently translated at 100.0% (673 of 673 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/uk/

Translated using Weblate (Ukrainian)

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SelectionPopupControllerDelegate.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/TabImpl.java

This patch implements to show the text selection's action UI and paste UI and execute selection actions by the user.

[chromium] Implement Text Selection

---

app/src/visionglass/cpp/DeviceDelegateVisionGlass.cpp

In particular:
* use the right horizontal FoV
* always use 1€ filter, even with uncalibrated controllers

Vision glass improvements

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/ChromiumPermissionDelegate.java

Implement new method in ChromiumPermissionDelegate that allows chromium backend to support media permissions such as microphone and camera access.
depends on https://github.com/Igalia/wolvic-chromium/pull/88

[Chromium] Support media permissions

---

app/src/common/chromium/com/igalia/wolvic/browser/api/impl/AutocompleteDelegateWrapper.kt
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/AutocompleteStorageProxy.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/ChromiumLoginStorageDelegate.kt
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/PromptDelegateImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/RuntimeImpl.java
app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java

- Implement Login UI & Login Selection UI in PromptDelegateImpl
- Implement Login DB in AutocompleteDelegateWrapper/AutocompleteStorageProxy/ChromiumLoginStorageDelegate
Fixes #1179

[chromium] Implement autocomplete's Login

---

app/src/visionglass/cpp/DeviceDelegateVisionGlass.cpp
app/src/visionglass/cpp/DeviceDelegateVisionGlass.h

This PR addresses the issues observed in the orientation of the aim (pointer). Among others:
1. pointer was not usable in multiwindow environment
2. pointer sometimes started to flicker
3. sometimes x axis got inverted
Fixes #1341

[VisionGlass] Fix pointer (aim) orientation

---

.github/workflows/build.yml

This PR addresses 2 warning that have been lately appearing in CI runs.

[CI] Fix warning in CI builds

---

app/src/main/res/values-ko/strings.xml

Currently translated at 100.0% (682 of 682 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/ko/

Translated using Weblate (Korean)

---

app/src/main/res/values-sv-rSE/strings.xml

Currently translated at 100.0% (682 of 682 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/sv/

Translated using Weblate (Swedish)

---

app/src/main/res/values-gl/strings.xml

Currently translated at 100.0% (673 of 673 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/gl/

Translated using Weblate (Galician)

---

app/src/visionglass/java/com/igalia/wolvic/AlignPhoneDialogFragment.java
app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java
app/src/visionglass/res/layout/dialog_align_phone.xml

Ensure that the calibration button follows the beam direction.
Make the calibration dialog not cancellable.

[Vision Glass] Small adjustments to calibration UI

---

app/src/openxr/cpp/DeviceDelegateOpenXR.cpp

We call it from a couple of places so it does make sense to refactor it in a helper method.

[OpenXR] Refactor the controllers ready callback

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/HamburgerMenuWidget.java

It is not implemented yet so it does not make any sense to have it in the UI.

[Chromium] Disable "Find in Page" in the UI

---

props.json

Create an entry for the 1.7.0 release.

Update props.json for 1.7.0

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/TabsWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/Windows.java
app/src/main/res/layout/tabs.xml
app/src/main/res/values/strings.xml

Fix #1298: Add a `Bookmark tabs` in tabs dialog, if clicked will bookmark all the selected tabs.

Allow bookmarking selected tabs in tabs dialog

---

props-chromium.json
props.json

"What's New" URL: https://wolvic.com/blog/release_1.7.1
Environments:
- `lobos`: Lobos, Fuerteventura by Simon Waldherr (CC BY-NC-SA)
- https://www.flickr.com/photos/simonwaldherr/51638698181/
- `nostalgiablue`: Colors of Nostalgia (Blue) by Duncan Rawlinson (CC BY-NC)
- https://www.flickr.com/photos/thelastminute/52426821655/
- `nostalgiaorange`: Colors of Nostalgia (Orange) by Duncan Rawlinson (CC BY-NC)
- https://www.flickr.com/photos/thelastminute/52425863182
- `fantasylandscape3`: Fantasy Landscape 3 by Giimann (CC BY)
- https://sketchfab.com/3d-models/fantasy-landscape-3-ded6e2bb0cfd4ef785b81fed2178c2fd

New props.json entry for 1.7.1

---

app/src/main/res/values-pt/strings.xml

Currently translated at 100.0% (688 of 688 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/pt/

Translated using Weblate (Portuguese)

---

app/src/main/res/values-ja/strings.xml

Currently translated at 100.0% (688 of 688 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/ja/

Translated using Weblate (Japanese)

---

app/src/main/res/values-pt-rBR/strings.xml

Currently translated at 100.0% (688 of 688 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/pt_BR/

Translated using Weblate (Portuguese (Brazil))

---

app/src/main/res/values-es-rES/strings.xml

Updated es-rES translations

---

app/src/main/res/values-ja/strings.xml

Updated ja translations

---

app/src/main/res/values-pt-rBR/strings.xml

Updated pt-rBR translations

---

app/src/main/res/values-fr/strings.xml

Updated fr translations

---

app/src/main/res/values-ko/strings.xml

Updated ko translations

---

app/src/main/res/values-pt/strings.xml

Updated pt translations

---

app/src/main/res/values-ru/strings.xml

Updated ru translations

---

app/src/main/res/values-zh-rCN/strings.xml

Updated zh-rCN translations

---

app/src/main/res/values-zh-rTW/strings.xml

Updated zh-rTW translations

---

app/src/main/res/values-gl/strings.xml

Updated gl translations

---

app/src/common/shared/com/igalia/wolvic/ui/views/library/BookmarksView.java

In addition to individual items, the collection of Bookmarks may contain folders. When filtering, we need to iterate each of these folders and present only the leaf items that match the current query.

Search in bookmark folders

---

app/src/common/shared/com/igalia/wolvic/audio/AndroidMediaPlayer.java
app/src/common/shared/com/igalia/wolvic/browser/Services.kt
app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/PermissionWidget.java
app/src/hvr/java/com/igalia/wolvic/PlatformActivity.java
app/src/noapi/java/com/igalia/wolvic/PlatformActivity.java
app/src/oculusvr/java/com/igalia/wolvic/PlatformActivity.java

Error messages should only be used for error conditions. Demote several messages to debug messages as they are not critical errors.

Sanitize error messages

---

app/src/main/cpp/WidgetResizer.cpp

Improve the visual appearance of the window resizer by adding a space between the resizing bars and the window, hiding the handles, increasing the touch area, and using theme colors.

New style for window resizer

---

app/src/main/res/values/strings.xml

Update the strings for the pointer mode setting to clarify what and how will be affected by it.
- `controller_options_pointer_mode`: Pointer control mode
- `developer_options_pointer_mode_tracked_pointer`: With controller or hand
- `developer_options_pointer_mode_tracked_eye`: With eye tracking

Update strings for pointer control mode

---

app/src/main/res/values-ta/strings.xml

Currently translated at 100.0% (700 of 700 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/ta/

Translated using Weblate (Tamil)

---

app/src/main/res/values-gl/strings.xml

Currently translated at 100.0% (700 of 700 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/gl/

Translated using Weblate (Galician) 

---

app/src/main/res/values-fr/strings.xml

Currently translated at 100.0% (700 of 700 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/fr/

Translated using Weblate (French)

---

app/src/main/res/values-es-rES/strings.xml

Currently translated at 100.0% (700 of 700 strings)
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/es/

Translated using Weblate (Spanish) 

---

props-chromium.json

Wolvic Chromium version: 1.2
Release announcement: https://wolvic.com/blog/chromium_release_1.2

Update props-chromium.json for the new release

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/PrivacyOptionsView.java

The state of permissions in the Privacy Settings can sometimes be inconsistent. This affects specially the location permissions, because the user is able to grant us access to either the "coarse" or the "fine" location using the system settings.
This change ensures that the UI is updated consistently both when we create this dialog and when a new permission is granted.

Consistent state of location permissions in the Settings

---

app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java

Unfortunately, the usual solutions for keeping the primary screen on (KEEP_SCREEN_ON, WakeLock) do not work with the Vision Glass, so we need to simulate a touch periodically while the device is connected and the application is active.

[Vision Glass] Keep screen on

---

props-chromium.json
props.json

Update props.json and props-chromium.json for the 1.8.1 release.

Update props for 1.8.1

---

experiences.json

Add experiences.json to the same server as our existing `props.json`.
This JSON file contains a list of suggested experiences and websites which will be displayed in the New Tab UI.

Add experiences.json

---

props-chromium.json
props.json

Update props for the next releaser 1.8.2 (Gecko) and 1.2.2 (Chromium).

Update props for 1.8.2/1.2.2 release

---

app/src/common/shared/com/igalia/wolvic/speech/MKSpeechRecognizer.java
app/src/common/shared/com/igalia/wolvic/speech/SpeechRecognizer.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/VoiceSearchWidget.java
app/src/hvrcommon/java/com/igalia/wolvic/speech/HVRSpeechRecognizer.java

Additional checks to ensure that the voice recognition system is always in a consistent state.

Stability of voice recognition

---

app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java

We recently added the possibility of switching the focus between windows by just hovering them. The problem is that switching everytime the window gets a focus is problematic because there are too many false positives. Users move their hands/controllers "erratically" so the focus might easily switch to another window when the users don't really want to.
By adding a 500msecs delay we'll remove most of them. From now on it's even possible to quickly hover windows alternatively and then focus won't change.

Added a delay to hover to focus

---

app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java
app/src/common/shared/com/igalia/wolvic/ui/widgets/settings/ControllerOptionsView.java
app/src/openxr/cpp/OpenXRInputSource.cpp

The movement in X axis was inverted compared to the Y axis in whatever scrolling mode (natural or reversed) selected by the user.
Apart from that we added an extra change to convert the ScrollDirection into an annotation which makes the code safer and easier to understand.
Fixes #1903

Homogenize the behaviour of horizontal and vertical scrolling 

---

app/src/main/cpp/ExternalBlitter.cpp

GL_OES_EGL_image_external textures are always treated as GL_RGBA (UNORM8) with no sRGB awareness. Android SurfaceTexture / ANativeWindow producers (in this case Gecko) often deliver frames in sRGB gamma (or YUV -> RGB already gamma encoded). When you sample in your shader, OpenGL does no sRGB->linear conversion because external textures do not support GL_SRGB8_* formats.
If you later write the sampled value into an sRGB framebuffer (e.g. GL_FRAMEBUFFER_SRGB enabled, or default surface configured as sRGB), the GPU applies another gamma curve -> double gamma correction -> image looks washed out / too bright.
Wolvic already disables that last gamma conversion by using glDisable(GL_FRAMEBUFFER_SRGB_EXT). That works for the widgets displayed by Wolvic (also splash screen and skybox) but seems …

Add an specific shader for Pico in the external blitter
